argo-cd:
  global:
    domain: argo.tecminal.com
  configs:
    params:
      server.insecure: "true"
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls: true
    extraArgs:
      - --insecure