descheduler:
  schedule: "*/30 * * * *"

  deschedulerPolicy:
    profiles:
      - name: default
        pluginConfig:
          - name: DefaultEvictor
            args:
              ignorePvcPods: true
              evictLocalStoragePods: false
          - name: PodLifeTime
            args:
              maxPodLifeTimeSeconds: 86400
          - name: LowNodeUtilization
            args:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 50
                memory: 50
                pods: 50
          - name: RemoveDuplicates
            args:
              excludeOwnerKinds:
                - ReplicaSet
        plugins:
          balance:
            enabled:
              - LowNodeUtilization
              - RemoveDuplicates
          deschedule:
            enabled:
              - PodLifeTime