descheduler:
  schedule: "*/30 * * * *"

  deschedulerPolicy:
    profiles:
      - name: default
        pluginConfig:
          - name: DefaultEvictor
            args:
              ignorePvcPods: true
              evictLocalStoragePods: false
          - name: PodLifeTime
            args:
              maxPodLifeTimeSeconds: 86400    # evict pods older than 24 hours
        plugins:
          balance:
            enabled:
              - LowNodeUtilization
              - RemoveDuplicates
          deschedule:
            enabled:
              - PodLifeTime