apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vijayvj6796/Kubernetes-learning
    targetRevision: main
    path: jellyfin-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true