apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    template:
      type: Opaque
  data:
    - secretKey: api-token
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
